# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/ila_fake_data_monitor/ila_fake_data_monitor.xci
# IP: The module: 'ila_fake_data_monitor' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/ila_fake_data_monitor/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_fake_data_monitor'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/ila_fake_data_monitor/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_fake_data_monitor'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/ila_fake_data_monitor/ila_fake_data_monitor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_fake_data_monitor'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/ila_fake_data_monitor/ila_fake_data_monitor.xci
# IP: The module: 'ila_fake_data_monitor' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/ila_fake_data_monitor/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_fake_data_monitor'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/ila_fake_data_monitor/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_fake_data_monitor'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/ila_fake_data_monitor/ila_fake_data_monitor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_fake_data_monitor'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
