# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/new/ETH_firmware/constrain/constrain_test_env_position.xdc

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/new/ETH_firmware/constrain/constrain_test_env_timing.xdc

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/new/ETH_firmware/source/ethernet_mac_interface/constrain/tri_mode_ethernet_mac_0_example_design.xdc

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/new/ETH_firmware/source/ethernet_mac_interface/constrain/tri_mode_ethernet_mac_0_user_phytiming.xdc

# IP: ip/vio_0/vio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet
