# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0.xci
# IP: The module: 'tri_mode_ethernet_mac_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0.xci
# IP: The module: 'tri_mode_ethernet_mac_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
