name: time_series_ensembles
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - plotly
  - sktime
  - statsmodels
  - jupyter
  - tqdm
  - python-kaleido
  - pmdarima
  - pip
  - pip:
    - pandas_datareader
    - yfinance
    - category_encoders
    - arch
    - joblib
    - dill
