# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/fifo_ETH_TX/fifo_ETH_TX.xci
# IP: The module: 'fifo_ETH_TX' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/fifo_ETH_TX/fifo_ETH_TX.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ETH_TX'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/fifo_ETH_TX/fifo_ETH_TX_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ETH_TX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/fifo_ETH_TX/fifo_ETH_TX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ETH_TX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/fifo_ETH_TX/fifo_ETH_TX.xci
# IP: The module: 'fifo_ETH_TX' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/fifo_ETH_TX/fifo_ETH_TX.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ETH_TX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/fifo_ETH_TX/fifo_ETH_TX_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ETH_TX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xx/work/KC705_DAQ/KC705_DAQ.srcs/sources_1/ip/fifo_ETH_TX/fifo_ETH_TX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ETH_TX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
